name: nyxx_extensions
version: 2.0.0-rc.5
description: Nyxx Extensions Module. Discord library for Dart. Simple, robust framework for creating discord bots for Dart language.
homepage: https://github.com/l7ssha/nyxx
repository: https://github.com/l7ssha/nyxx
documentation: https://github.com/l7ssha/nyxx/wiki
issue_tracker: https://github.com/l7ssha/nyxx/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: "^0.13.1"
  nyxx:
    git:
      url: https://github.com/Technicolor-creamsicle/nyxx/
      path: nyxx/
      

dev_dependencies:
  test: "^1.16.8"
